name: "vite-apache"
services:
  node:
    image: node:22.12
    restart: unless-stopped
    tty: true
    stdin_open: true
    working_dir: /appvite
    user: 1000:1000
    ports:
      - "8282:5173"
    volumes:
      - ./vite:/appvite
  scss:
    build:
      context: .
      dockerfile: Dockerfile-scss
    tty: true
    stdin_open: true
    working_dir: /app
    environment:
      user: 1000:1000
    volumes:
      - ./vite:/app
  apache:
    image: httpd
    tty: true
    stdin_open: true
    working_dir: /usr/local/apache2/htdocs/
    volumes:
      - .:/usr/local/apache2/htdocs/
    ports:
      - "99:80"
  demo:
    build:
      context: .
      dockerfile: Dockerfile-web
    tty: true
    stdin_open: true
    working_dir: /app
    volumes:
      - ./web:/app
    ports:
      - "8686:8080"